export { default as Navbar } from './Navbar/Navbar'
export { default as About } from './About/About'
export { default as Analysis } from './Analysis/Analysis'
export { default as BackToTop } from './BackToTop/BackToTop'
export { default as Banner } from './Banner/Banner'
export { default as Blog } from './Blog/Blog'
export { default as Boosting } from './Boosting/Boost'
export { default as ChooseUs } from './ChooseUs/ChooseUs'
export { default as Features } from './Feature/Features'
export { default as Footer } from './Footer/Footer'
export { default as NewsLatter } from './NewsLatter/NewsLatter'
export { default as Projects } from './Projects/Projects'
export { default as Service } from './Services/Service'
export { default as Sidebar } from './Sidebar/Sidebar'
export { default as Team } from './Team/Team'
export { default as Testimonial } from './Testimonial/Testimonial'
export { default as Contact } from './Contact/Contact'

